pipeline:

  build:
    image: purplekarrot/arm-linux-gnueabihf
    commands:
      - make

  test-UC8100:
    image: yanagiis/drone-deploy-to-device
    group: test
    pull: true
    device_type: UC8100
    device_image: FB_UC8100_V2.0_Build_17062219.img
    script: test.sh
    source: main

  test-UC8100ME:
    image: yanagiis/drone-deploy-to-device
    group: test
    pull: true
    device_type: UC8100ME
    device_image: FWR_UC8100ME_V2.1_Build_17041918.img
    script: test.sh
    source: main


  # slack:
  #   image: plugins/slack
  #   webhook: https://hooks.slack.com/services/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
  #   channel: droneci
  #   when:
  #     status: [ success, failure ]
  #   template: >
  #     {{#success build.status}}
  #       Build <{{build.link}}|{{build.number}}> succeeded. Good job.
  #     {{else}}
  #       Build <{{build.link}}|{{build.number}}> failed. Fix me please.
  #     {{/success}}
  #     *Repo*
  #       {{repo.owner}}/{{repo.name}} ({{build.branch}}) by {{build.author}}
  #     *Commit*
  #       {{build.message}}
