pipeline:
  build:
    image: gcc
    commands:
      - make
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: devops
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Good job.
      {{else}}
        Build {{build.number}} failed. Fix me please.
      {{/success}}
      *Author* {{build.author}} *Branch* {{build.branch}} *Repo* {{repo.owner}}/{{repo.name}}
